Actually use SITEMAP_INDEX_NAME from documentation
just-work/django-sitemap-generate pull request #22
Opened 2021-03-16 17:22 UTC by verschmelzen

- Add SITEMAPS_VIEW_NAME setting to also specify sitemap views from
  instead of hardcoded 'django.contrib.sitemaps.views.sitemap'
- Move `load_string` for SITEMAP_MAPPING to `SitemapGenerator`
- Keep old values as defaults

2021-03-17 05:08 UTC, tumb1er requested changes
Great changes! But there are some more improvements to be done.
Are you interested in PR improving? I can done it myself in a few days.

2021-03-17 05:08 UTC, tumb1er commented on sitemap_generate/generator.py
> +            else getattr(settings, 'SITEMAP_INDEX_NAME', 'sitemap-index')
It may be hard to find default values if they are specified in-place. This should be done as a separate app settings module.

2021-03-17 05:08 UTC, tumb1er commented on sitemap_generate/generator.py
> +                 index_url_name: Optional[str] = None,
`mediapath` and `storage` should be defaulted the same way.

2021-03-18 10:21 UTC, verschmelzen commented
Media path, storage and others have their defaults at `default_settings.py`. README.md updated.

Please let me know if there are improvements that can be done.

2021-03-19 13:30 UTC, tumb1er approved these changes

2021-03-19 13:32 UTC, merged

2021-03-19 13:54 UTC, tumb1er commented
Released with 0.3.0

@verschmelzen thank you!